apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: acme-platform
      app.kubernetes.io/component: cnpg
