apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/part-of: acme-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarqube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarqube
    spec:
      serviceAccountName: sonarqube
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: sonarqube
          image: docker.io/library/sonarqube:lts-community
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
            - name: SONAR_WEB_JAVAOPTS
              value: -Xmx512m
            - name: SONAR_CE_JAVAOPTS
              value: -Xmx256m
            - name: SONAR_SEARCH_JAVAOPTS
              value: -Xmx512m -Xms256m
          volumeMounts:
            - name: data
              mountPath: /opt/sonarqube/data
            - name: ext
              mountPath: /opt/sonarqube/extensions
            - name: logs
              mountPath: /opt/sonarqube/logs
          startupProbe:
            httpGet:
              path: /api/system/status
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/system/status
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/system/status
              port: http
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              cpu: 200m
              memory: 2Gi
            limits:
              cpu: "1"
              memory: 3Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: ext
          emptyDir: {}
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
spec:
  selector:
    app.kubernetes.io/name: sonarqube
  ports:
    - name: http
      port: 9000
      targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
spec:
  to:
    kind: Service
    name: sonarqube
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
