FROM registry.access.redhat.com/ubi9/nodejs-20:latest
WORKDIR /opt/app-root/src
COPY package.json server.js ./
USER 1001
ENV PORT=${{ values.port }}
ENV BACKEND_URL=${{ values.backendUrl }}
EXPOSE ${{ values.port }}
CMD ["node", "server.js"]
