# Cluster-scoped. Token Secret is created by scripts/seed-vault.py (not in git).
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  labels:
    app.kubernetes.io/part-of: acme-platform
    app.kubernetes.io/component: secrets
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secrets
      version: v2
      auth:
        tokenSecretRef:
          name: vault-eso-token
          key: token
          namespace: external-secrets
