{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "rhdh.namespace" . }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
    {{- if .Values.mesh.ambient }}
    istio.io/dataplane-mode: ambient
    {{- end }}
{{- end }}
