apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: saas-stubs
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: saas-stubs
    files:
      - server.py
    options:
      disableNameSuffixHash: true
