apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ldap
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - anyuid-rolebinding.yaml
  - deployment.yaml
configMapGenerator:
  - name: openldap-bootstrap
    files:
      - bootstrap.ldif
    options:
      disableNameSuffixHash: true
