sonar.projectKey=${{ values.sonarProjectKey }}
sonar.projectName=${{ values.appName }}
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.host.url=${{ values.sonarHostUrl }}
sonar.java.binaries=target/classes
